paths:
  /Eventos:
    post:
      tags:
        - Evento
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Evento.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Evento'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Evento'
      deprecated: false
    put:
      tags:
        - Evento
      summary: >-
        Update an existing model instance or insert a new one into the data
        source.
      operationId: Evento.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Evento'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Evento'
      deprecated: false
    get:
      tags:
        - Evento
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Evento.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Evento'
      deprecated: false
  '/Eventos/{id}/exists':
    get:
      tags:
        - Evento
      summary: Check whether a model instance exists in the data source.
      operationId: 'Evento.exists__get_Eventos_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Eventos/{id}':
    head:
      tags:
        - Evento
      summary: Check whether a model instance exists in the data source.
      operationId: 'Evento.exists__head_Eventos_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Evento
      summary: Find a model instance by id from the data source.
      operationId: Evento.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Evento'
      deprecated: false
    delete:
      tags:
        - Evento
      summary: Delete a model instance by id from the data source.
      operationId: Evento.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Evento
      summary: >-
        Update attributes for a model instance and persist it into the data
        source.
      operationId: Evento.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Evento'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Evento'
      deprecated: false
  /Eventos/findOne:
    get:
      tags:
        - Evento
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Evento.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Evento'
      deprecated: false
  /Eventos/update:
    post:
      tags:
        - Evento
      summary: Update instances of the model matched by where from the data source.
      operationId: Evento.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Evento'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /Eventos/count:
    get:
      tags:
        - Evento
      summary: Count instances of the model matched by where from the data source.
      operationId: Evento.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /Eventos/change-stream:
    post:
      tags:
        - Evento
      summary: Create a change stream.
      operationId: Evento.createChangeStream__post_Eventos_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - Evento
      summary: Create a change stream.
      operationId: Evento.createChangeStream__get_Eventos_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
definitions:
  Evento:
    properties:
      nome:
        type: string
      active:
        type: boolean
      id:
        type: number
        format: double
    additionalProperties: false
  x-any:
    properties: {}
swagger: '2.0'
info:
  x-ibm-name: server
  version: 1.0.0
  title: server
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth definition:
    type: oauth2
    description: ''
    flow: password
    scopes:
      view_branches: ver conteudo
    tokenUrl: 'https://127.0.0.1:4002/sb/oauth-end/oauth2/token'
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientSecretHeader: []
    oauth definition:
      - view_branches
    clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
